In [1]:
import os
from cnf import CNF
import numpy as np

In [2]:
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Categorical

In [63]:
class Net(nn.Module):
    def __init__(self, h=5):
        super(Net, self).__init__()
        self.lin = nn.Linear(4, h)
        self.dropout = nn.Dropout(0.5)
        self.lin2 = nn.Linear(h, 1)
    def forward(self, x):
        x = self.lin(x)
        x = F.relu(self.dropout(x))
        x = self.lin2(x)
        return x

In [4]:
def init_net(model):
    with torch.no_grad():
        model.lin.weight[0, 0] = 10
        model.lin2.weight[0, 0] = -1

In [5]:
class Net2(nn.Module):
    def __init__(self):
        super(Net2, self).__init__()
        self.lin = nn.Linear(4, 1)
    def forward(self, x):
        x = self.lin(x)
        return x

In [6]:
def init_net2(policy):
    with torch.no_grad():
        policy.lin.weight[0, 0] = -1
        policy.lin.weight[0, 1] = 0
        policy.lin.weight[0, 2] = 0
        policy.lin.weight[0, 3] = 0
        policy.lin.bias[0] = 0

In [17]:
def load_dir(path):
    data = []
    for filename in os.listdir(path):
        name, ext = os.path.splitext(filename)
        if ext != '.cnf':
            continue
        f = CNF.from_file(os.path.join(path, filename))
        data.append(f)
    return data

In [8]:
class WalkSATLN:
    def __init__(self, policy, max_tries, max_flips, p=0.5, discount=0.5):
        self.policy = policy
        self.max_tries = max_tries
        self.max_flips = max_flips
        self.p = p
        self.discount = discount
        self.flips_to_solution = []
        self.backflips = []
        self.unsat_clauses = []
        self.age = []
        self.last_10 = []
        self.sol = []
        
    def compute_true_lit_count(self, clauses):
        n_clauses = len(clauses)
        true_lit_count = [0] * n_clauses
        for index in range(n_clauses):
            for literal in clauses[index]:
                if self.sol[abs(literal)] == literal:
                    true_lit_count[index] += 1
        return true_lit_count
    
    def select_variable_reinforce(self, x):
        logit = self.policy(x)
        prob = F.softmax(logit, dim=0)
        dist = Categorical(prob.view(-1))
        v = dist.sample()
        return v, dist.log_prob(v)
    
    def do_flip(self, literal, occur_list):
        for i in occur_list[literal]:
            self.true_lit_count[i] += 1
        for i in occur_list[-literal]:
            self.true_lit_count[i] -= 1
        self.sol[abs(literal)] *= -1
        
    def stats_per_clause(self, f, unsat_clause):
        """ computes the featutes needed for the model
        """ 
        r = f.n_variables/ len(f.clauses)
        variables = [abs(v) for v in unsat_clause]
        breaks = np.zeros(len(variables))
        last_5 = self.last_10[:5]
        for i, literal in enumerate(unsat_clause):
            broken_count = 0
            for index in f.occur_list[-literal]:
                if self.true_lit_count[index] == 1:
                    broken_count += 1
            breaks[i] = broken_count
        in_last_10 = np.array([int(v in self.last_10) for v in variables]) 
        age = np.array([self.age[v] for v in variables])/(self.age[0] + 1)
        in_last_5 = np.array([int(v in last_5) for v in variables]) 
        return np.stack([breaks, in_last_10, in_last_5, age], axis=1)
    
    def walksat_step(self, f, unsat_clause):
        """Returns chosen literal"""
        broken_min = float('inf')
        min_breaking_lits = []
        for literal in unsat_clause:
            broken_count = 0
            for index in f.occur_list[-literal]:
                if self.true_lit_count[index] == 1:
                    broken_count += 1
                if broken_count > broken_min:
                    break
            if broken_count < broken_min:
                broken_min = broken_count
                min_breaking_lits = [literal]
            elif broken_count == broken_min:
                min_breaking_lits.append(literal)
        return abs(random.choice(min_breaking_lits))
    
    def reinforce_step(self, f, unsat_clause):
        x = self.stats_per_clause(f, unsat_clause)
        x = torch.from_numpy(x).float()
        index, log_prob = self.select_variable_reinforce(x)
        literal = unsat_clause[index]
        return literal, log_prob
    
    def generate_episode_reinforce(self, f, walksat):
        self.sol = [x if random.random() < 0.5 else -x for x in range(f.n_variables + 1)]
        self.true_lit_count = self.compute_true_lit_count(f.clauses)
        self.age = np.zeros(f.n_variables + 1)
        log_probs = []
        flips = 0
        flipped = set()
        backflipped = 0
        while flips < max_flips:
            unsat_clause_indices = [k for k in range(len(f.clauses)) if self.true_lit_count[k] == 0]
            sat = not unsat_clause_indices
            if sat:
                break
            unsat_clause = f.clauses[random.choice(unsat_clause_indices)]
            log_prob = None
            if random.random() < self.p:
                literal = random.choice(unsat_clause)
            else:
                if walksat:
                    literal = self.walksat_step(f, unsat_clause)   
                else:
                    literal, log_prob = self.reinforce_step(f, unsat_clause)
                v = abs(literal)
                if v not in flipped:
                    flipped.add(v)
                else:
                    backflipped += 1
                self.last_10.insert(0, v)
                self.last_10 = self.last_10[:10]
                self.age[v] = flips
            self.do_flip(literal, f.occur_list)
            flips += 1
            self.age[0] = flips
            log_probs.append(log_prob)
        return sat, flips, backflipped, log_probs

    def reinforce_loss(self, log_probs_list):
        T = len(log_probs_list)
        log_probs_filtered = []
        mask = np.zeros(T, dtype=bool)
        for i, x in enumerate(log_probs_list):
            if x is not None:
                log_probs_filtered.append(x)
                mask[i] = 1

        log_probs = torch.stack(log_probs_filtered)
        p_rewards = self.discount ** torch.arange(T - 1, -1, -1, dtype=torch.float32, device=log_probs.device)
        return -torch.mean(p_rewards[torch.from_numpy(mask).to(log_probs.device)] * log_probs)

    def generate_episodes(self, f, walksat=False):
        flips_stats = []
        losses = []
        backflips = []
        num_sols = 0
        for i in range(self.max_tries):
            sat, flips, backflipped, log_probs = self.generate_episode_reinforce(f, walksat)
            flips_stats.append(flips)
            backflips.append(backflipped)
            if sat and flips > 0 and not all(map(lambda x: x is None, log_probs)):
                loss = self.reinforce_loss(log_probs)
                losses.append(loss)
            num_sols += sat    
        if losses:
            losses = torch.stack(losses).sum()  
        return np.mean(flips), np.mean(backflips), losses, num_sols/self.max_tries
    
    
    def evaluate(self, data, walksat=False):
        mean_flips = []
        mean_backflips = []
        mean_losses = []
        accuracy = []
        self.policy.eval()
        for f in data:
            flips, backflips, losses, acc = self.generate_episodes(f, walksat)
            mean_flips.append(flips)
            mean_backflips.append(backflips)
            if losses:
                mean_losses.append(losses.item())
            accuracy.append(acc)
            mean_loss = None
            if mean_losses:
                mean_loss = np.mean(mean_losses)
        print(np.mean(mean_flips), np.mean(mean_backflips), mean_loss, np.mean(accuracy))
        
    def train_epoch(self, optimizer, data):
        losses = []
        for f in data:
            self.policy.train()
            flips, backflips, loss, acc = self.generate_episodes(f)
            if acc > 0:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                losses.append(loss.item())
        print(np.mean(losses))

In [75]:
def change_lr(optimizer, lr):
    for g in optimizer.param_groups:
        g['lr'] = lr

In [76]:
train_ds = load_dir("../data/rand3sat/10-43")
#val_ds = load_dir("../data/rand3sat/25-106")

In [90]:
train_ds = load_dir("../data/rand3sat/25-106")
#val_ds = load_dir("../data/rand3sat/25-106")
val_ds = train_ds[1900:]
train_ds = train_ds[:1900]
len(train_ds), len(val_ds)

(1900, 100)

In [108]:
policy = Net(10)
optimizer = optim.RMSprop(policy.parameters(), lr=0.001, weight_decay=1e-5)
max_tries = 10
max_flips = 10000

In [13]:
#init_net(policy)

In [79]:
#train_ds = load_dir("../data/kcolor/4-15-0.5/")
#train_ds = load_dir("../data/kcolor/3-10-0.5/")
#val_ds = train_ds[1900:]
#train_ds = train_ds[:1900]
#len(train_ds), len(val_ds)

In [109]:
#init_net(policy)
[p for p in policy.parameters()]

[Parameter containing:
 tensor([[-2.8843e-01, -4.1706e-02, -4.0902e-01, -4.0046e-01],
         [ 4.1862e-01, -4.7143e-01,  3.7906e-01,  1.9453e-01],
         [ 3.1812e-01,  4.3379e-01,  3.3929e-01, -4.5520e-04],
         [-1.9672e-01, -3.4323e-03, -2.9250e-01,  7.8363e-02],
         [ 2.8369e-01, -4.7228e-01,  8.2873e-02,  2.7496e-01],
         [ 7.6970e-02,  1.3853e-01,  3.4963e-01,  1.0485e-01],
         [ 4.4656e-01,  3.7772e-01,  5.1349e-02, -9.9553e-02],
         [ 1.1407e-01,  1.6547e-01, -8.5185e-02, -2.9410e-01],
         [-4.9991e-01,  1.9581e-01, -4.1957e-01, -3.1421e-01],
         [-3.8264e-01,  2.7012e-01, -3.2084e-01,  3.0505e-02]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.2111, -0.4324, -0.4028, -0.4429,  0.2714, -0.3596,  0.4745,  0.3559,
          0.2470, -0.3011], requires_grad=True),
 Parameter containing:
 tensor([[-0.0391,  0.2282,  0.2711, -0.2690, -0.1782,  0.0278, -0.1621,  0.0800,
           0.1487,  0.2014]], requires_grad=True),
 Paramet

In [110]:
max_tries = 10
max_flips = 10000

In [117]:
ls = WalkSATLN(policy, max_tries, max_flips, p=0.5, discount=.9)

In [118]:
for i in range(3):
    ls.evaluate(val_ds, walksat=True)

70.6 20.613000000000003 None 1.0
73.03 20.213 None 1.0
75.92 20.04 None 1.0


In [ ]:
for j in range(15):
    ls.train_epoch(optimizer, train_ds)
    ls.evaluate(val_ds)

0.3091766284200314
114.57 47.288999999999994 0.370013660043478 1.0
0.31820133802456485
137.13 53.012 0.3412149280309677 1.0
0.2966167991147622
140.01 60.03500000000001 0.35937279734760524 1.0
0.3032011936183431
130.09 53.571000000000005 0.3630289803445339 1.0
0.2910972425689627
131.36 55.27199999999999 0.3665674816071987 1.0
0.2852937422898647
135.94 52.823 0.36288382899947463 1.0
0.28650957460956356
122.65 55.926 0.3603705955483019 1.0
0.29238330063214035
135.41 58.82599999999999 0.32799783438444136 0.9990000000000001
0.2740555283515469
147.25 50.526 0.34662231797352433 1.0
0.28442665591345806
123.98 54.989000000000004 0.354642024487257 1.0
0.27609858374601526
147.89 54.144 0.36782012317329643 1.0
0.26977943506582003
128.12 50.58599999999999 0.3726365429349244 1.0
0.2670270506738636
139.62 54.981 0.35227100711315873 1.0


In [ ]:
for i in range(3):
    ls.evaluate(val_ds)

In [ ]:
for j in range(5):
    ls.train_epoch(optimizer, train_ds)

In [ ]:
for i in range(3):
    ls.evaluate(val_ds)

In [116]:
#.8
for i in range(3):
    ls.evaluate(val_ds)

109.29 50.015 0.18105776796117426 1.0
123.68 57.725 0.1695455040037632 1.0
146.51 57.57400000000001 0.1725869902037084 1.0


In [107]:
# .25
for i in range(3):
    ls.evaluate(val_ds)

112.61 55.934000000000005 0.024347269870049787 1.0
143.77 54.71800000000001 0.02459714886987058 1.0
162.96 57.135 0.02394227594093536 1.0


In [96]:
# discount 0.4
for i in range(3):
    ls.evaluate(val_ds)

138.3 55.078999999999986 0.028947463862859877 1.0
148.99 52.894000000000005 0.024711168918584006 1.0
117.32 51.46400000000001 0.0268075664745993 1.0


In [97]:
for j in range(5):
    ls.train_epoch(optimizer, train_ds)

0.026004379572403098
0.02347291780349463
0.025463704187972516
0.024239899521168187
0.02653773764850341


In [98]:
for i in range(3):
    ls.evaluate(val_ds)

128.6 51.41 0.04875243358150328 1.0
144.01 54.299 0.04005843963619554 1.0
126.26 54.808000000000014 0.031751742220658345 1.0


In [88]:
[p for p in policy.parameters()]

[Parameter containing:
 tensor([[-2.3997, -0.3695, -0.0556, -1.4425],
         [ 3.6482,  0.1932,  0.8497,  0.0839],
         [ 3.3826, -0.1052,  1.6315, -0.2734],
         [ 3.0301,  0.5785,  1.2932,  0.7446],
         [ 3.3367,  0.3708,  1.7035,  0.0976]], requires_grad=True),
 Parameter containing:
 tensor([ 2.3543, -2.8193, -2.6967, -3.0457, -2.9206], requires_grad=True),
 Parameter containing:
 tensor([[ 3.8875, -4.8629, -4.4125, -5.0814, -5.0216]], requires_grad=True),
 Parameter containing:
 tensor([0.0033], requires_grad=True)]

In [57]:
#train_ds = load_dir("../data/rand3sat/25-106")
train_ds = load_dir("../data/kclique/3-5-0.2/")
val_ds = train_ds[1800:]
train_ds = train_ds[:1800]
len(train_ds), len(val_ds)

(1800, 160)

In [64]:
policy = Net()
optimizer = optim.RMSprop(policy.parameters(), lr=0.001, weight_decay=0)
#init_net2(policy)
max_tries = 10
max_flips = 10000

In [65]:
[p for p in policy.parameters()]

[Parameter containing:
 tensor([[-0.4709, -0.4295, -0.1632,  0.1809],
         [ 0.2581,  0.4259, -0.3950, -0.3905],
         [-0.3567, -0.0589, -0.4169, -0.3181],
         [-0.0271, -0.4185,  0.4220,  0.3886],
         [ 0.4473, -0.2143, -0.3733, -0.0181]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1345, -0.3361, -0.2100,  0.0532,  0.2223], requires_grad=True),
 Parameter containing:
 tensor([[-0.0039,  0.4246, -0.4139, -0.4040,  0.2209]], requires_grad=True),
 Parameter containing:
 tensor([-0.3221], requires_grad=True)]

In [66]:
ls = WalkSATLN(policy, max_tries, max_flips, p=0.5)

In [61]:
for i in range(3):
    ls.evaluate(val_ds, walksat=True)

35.46875 10.08375 None 1.0
34.3 10.196250000000001 None 1.0
36.10625 10.094999999999999 None 1.0


In [67]:
for i in range(3):
    ls.evaluate(val_ds)

191.0625 78.3 0.4523022493813187 1.0
199.725 80.59625 0.4411004173569381 1.0
182.94375 78.62937500000001 0.4927808415144682 1.0


In [68]:
for j in range(15):
    ls.train_epoch(optimizer, train_ds)
    ls.evaluate(val_ds)

0.4302416797582474
45.4375 12.6175 0.34005261920392515 1.0
0.24499379313292188
40.825 11.126249999999999 0.29827029216103257 1.0
0.2097663758788258
35.71875 10.28875 0.29054862991906705 1.0
0.21226228304828207
38.05625 9.68 0.26661623902618886 1.0
0.20121002536474003
34.975 9.391875 0.24267770475707948 1.0
0.19861296176392998
36.31875 9.13875 0.23618312077596784 1.0
0.1950332091645234
36.51875 8.960625 0.2220528768375516 1.0
0.19326598833522035
33.96875 8.698125000000001 0.2086977020604536 1.0
0.19179700914227094
34.28125 8.068125 0.19989559159148484 1.0
0.1934044715630201
36.7375 8.42125 0.1954457562416792 1.0
0.19226405694615095
37.25 8.408750000000001 0.18346511863637716 1.0
0.18701020144055494
32.975 8.34375 0.18828705131309106 1.0
0.18385154952450344
36.275 8.055625000000001 0.1708696506684646 1.0
0.1842433035528908
34.3375 8.20625 0.15983921515289695 1.0
0.18066280145430938
33.84375 7.78125 0.14616115840617566 1.0


In [69]:
for j in range(10):
    ls.train_epoch(optimizer, train_ds)
    ls.evaluate(val_ds)

0.1900133056889495
28.26875 7.88125 0.1598966016783379 1.0
0.18571612565622975
35.28125 7.835625 0.1493968229740858 1.0
0.18074108219783133
32.84375 7.983125000000001 0.13599841308314353 1.0
0.1765854917262267
30.14375 7.8050000000000015 0.13796455648262054 1.0
0.1810314372052542
32.24375 7.433750000000001 0.1414280461729504 1.0
0.1801449193000897
34.96875 8.31625 0.13618679160717875 1.0
0.18026766701497965
32.49375 8.1125 0.13329387855483218 1.0
0.16985321175384646
34.0 7.7425000000000015 0.14587803810136393 1.0
0.17907653575944196
33.9125 7.766875000000001 0.11901606121100486 1.0
0.17503390257945284
33.125 7.799375 0.12751176658202895 1.0


In [70]:
for i in range(3):
    ls.evaluate(val_ds)

36.04375 7.583125000000001 0.12679847616236656 1.0
31.39375 7.8125 0.12810946155805142 1.0
35.2125 8.2875 0.1146646652603522 1.0


In [71]:
[p for p in policy.parameters()]

[Parameter containing:
 tensor([[-2.4546, -0.5375, -0.4934, -0.9594],
         [ 0.0429,  0.2279, -0.4182, -0.5133],
         [-0.3567, -0.0589, -0.4169, -0.3181],
         [ 2.0970,  0.3866,  0.7357,  0.1994],
         [ 2.2783,  0.5436,  0.7418,  0.2649]], requires_grad=True),
 Parameter containing:
 tensor([ 2.4530, -0.5514, -0.2100, -1.3267, -1.5038], requires_grad=True),
 Parameter containing:
 tensor([[ 6.5825,  0.2712, -0.4139, -3.4072, -2.8941]], requires_grad=True),
 Parameter containing:
 tensor([0.0931], requires_grad=True)]

In [72]:
change_lr(optimizer, lr=0.0001)

In [73]:
for j in range(5):
    ls.train_epoch(optimizer, train_ds)
    ls.evaluate(val_ds)

0.17591446167090907
32.45 7.956874999999999 0.1163583088782616 1.0
0.17709127300496524
34.25625 7.95875 0.14412777799880133 1.0
0.17739224164876052
32.79375 8.01625 0.13437118483707308 1.0
0.17430420260048574
32.46875 7.830625 0.12468807835830376 1.0
0.17605081266775313
35.6875 8.038749999999999 0.13829632542910986 1.0


In [74]:
for i in range(3):
    ls.evaluate(val_ds)

36.06875 7.825625 0.120837081305217 1.0
30.125 7.878750000000001 0.133009365783073 1.0
39.49375 8.409375 0.1410188393376302 1.0
